#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Messaging.Resource", IsApplication=true)]

namespace Messaging
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_storm_apple_mac_blue_symbol_8281_1080x1920 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background3 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background4 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background5 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background6 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_info = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int LightingStrike = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int AddContactBackButton = 2131034118;
			
			// aapt resource value: 0x7f050019
			public const int AddContactButton = 2131034137;
			
			// aapt resource value: 0x7f050005
			public const int AddNewContactButton = 2131034117;
			
			// aapt resource value: 0x7f050037
			public const int AddNewUnitBackButton = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int AddNewUnitSubmitButton = 2131034168;
			
			// aapt resource value: 0x7f05004c
			public const int AddUnitButton = 2131034188;
			
			// aapt resource value: 0x7f050022
			public const int BackButton = 2131034146;
			
			// aapt resource value: 0x7f050003
			public const int ContactInput = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int FriendRequestsTitle = 2131034119;
			
			// aapt resource value: 0x7f050017
			public const int GoToFriendRequestsButton = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int GoToUnitButton = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int ListView = 2131034136;
			
			// aapt resource value: 0x7f05001f
			public const int MessageInput = 2131034143;
			
			// aapt resource value: 0x7f050025
			public const int MessengerLoader = 2131034149;
			
			// aapt resource value: 0x7f05003d
			public const int NewEmailInput = 2131034173;
			
			// aapt resource value: 0x7f05003c
			public const int NewEmailLabel = 2131034172;
			
			// aapt resource value: 0x7f050041
			public const int NewPasswordConfirmInput = 2131034177;
			
			// aapt resource value: 0x7f050040
			public const int NewPasswordConfirmLabel = 2131034176;
			
			// aapt resource value: 0x7f05003f
			public const int NewPasswordInput = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int NewPasswordLabel = 2131034174;
			
			// aapt resource value: 0x7f050032
			public const int NewUnitEndDateInput = 2131034162;
			
			// aapt resource value: 0x7f050031
			public const int NewUnitEndDateLabel = 2131034161;
			
			// aapt resource value: 0x7f050028
			public const int NewUnitIdInput = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int NewUnitIdLabel = 2131034151;
			
			// aapt resource value: 0x7f05002c
			public const int NewUnitLecturerInput = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int NewUnitLecturerLabel = 2131034155;
			
			// aapt resource value: 0x7f050035
			public const int NewUnitLocationInput = 2131034165;
			
			// aapt resource value: 0x7f050034
			public const int NewUnitLocationLabel = 2131034164;
			
			// aapt resource value: 0x7f05002a
			public const int NewUnitNameInput = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int NewUnitNameLabel = 2131034153;
			
			// aapt resource value: 0x7f05002f
			public const int NewUnitStartDateInput = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int NewUnitStartDateLabel = 2131034158;
			
			// aapt resource value: 0x7f050026
			public const int NewUnitTitle = 2131034150;
			
			// aapt resource value: 0x7f05003b
			public const int NewUsernameInput = 2131034171;
			
			// aapt resource value: 0x7f05003a
			public const int NewUsernameLabel = 2131034170;
			
			// aapt resource value: 0x7f050021
			public const int RefreshButton = 2131034145;
			
			// aapt resource value: 0x7f050042
			public const int RegisterBackButton = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int RegisterSubmitButton = 2131034179;
			
			// aapt resource value: 0x7f050039
			public const int RegisterTitle = 2131034169;
			
			// aapt resource value: 0x7f050023
			public const int SendButton = 2131034147;
			
			// aapt resource value: 0x7f05004b
			public const int UnitBackButton = 2131034187;
			
			// aapt resource value: 0x7f050057
			public const int UnitEndDate = 2131034199;
			
			// aapt resource value: 0x7f050056
			public const int UnitEndDateLabel = 2131034198;
			
			// aapt resource value: 0x7f05004f
			public const int UnitId = 2131034191;
			
			// aapt resource value: 0x7f05004e
			public const int UnitIdLabel = 2131034190;
			
			// aapt resource value: 0x7f050053
			public const int UnitLecturer = 2131034195;
			
			// aapt resource value: 0x7f050052
			public const int UnitLecturerLabel = 2131034194;
			
			// aapt resource value: 0x7f05004a
			public const int UnitListView = 2131034186;
			
			// aapt resource value: 0x7f050059
			public const int UnitLocation = 2131034201;
			
			// aapt resource value: 0x7f050058
			public const int UnitLocationLabel = 2131034200;
			
			// aapt resource value: 0x7f050051
			public const int UnitName = 2131034193;
			
			// aapt resource value: 0x7f050050
			public const int UnitNameLabel = 2131034192;
			
			// aapt resource value: 0x7f05004d
			public const int UnitPageTitle = 2131034189;
			
			// aapt resource value: 0x7f050055
			public const int UnitStartDate = 2131034197;
			
			// aapt resource value: 0x7f050054
			public const int UnitStartDateLabel = 2131034196;
			
			// aapt resource value: 0x7f05005a
			public const int UnitViewBackButton = 2131034202;
			
			// aapt resource value: 0x7f050014
			public const int button1 = 2131034132;
			
			// aapt resource value: 0x7f05000c
			public const int contactId = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int contactName = 2131034125;
			
			// aapt resource value: 0x7f05001e
			public const int contactNameHeader = 2131034142;
			
			// aapt resource value: 0x7f050049
			public const int courseLocation = 2131034185;
			
			// aapt resource value: 0x7f050048
			public const int courseName = 2131034184;
			
			// aapt resource value: 0x7f050013
			public const int editText1 = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int editText2 = 2131034129;
			
			// aapt resource value: 0x7f050047
			public const int finishDate = 2131034183;
			
			// aapt resource value: 0x7f05000a
			public const int gridLayout1 = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int imageButton1 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int imageView1 = 2131034123;
			
			// aapt resource value: 0x7f050016
			public const int linearLayout1 = 2131034134;
			
			// aapt resource value: 0x7f050009
			public const int listView1 = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int loginLoader = 2131034127;
			
			// aapt resource value: 0x7f05001c
			public const int message = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int messageListView = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int messageTime = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int registerButton = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int relativeLayout2 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int relativeLayout3 = 2131034116;
			
			// aapt resource value: 0x7f050024
			public const int relativeLayout4 = 2131034148;
			
			// aapt resource value: 0x7f05002d
			public const int relativeLayout5 = 2131034157;
			
			// aapt resource value: 0x7f050030
			public const int relativeLayout6 = 2131034160;
			
			// aapt resource value: 0x7f050033
			public const int relativeLayout7 = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int relativeLayout8 = 2131034166;
			
			// aapt resource value: 0x7f05001b
			public const int senderName = 2131034139;
			
			// aapt resource value: 0x7f050046
			public const int startDate = 2131034182;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int textView2 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int textView3 = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int textView4 = 2131034126;
			
			// aapt resource value: 0x7f050044
			public const int unitId = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int unitLecturer = 2131034181;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddContact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FriendRequestsView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listview_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int message = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Messenger = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Messenger2 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NewUnitView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int RegisterView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int unitlistveiw_row = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Units = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int UnitView = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
